name: Deploy Static Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        # Capture Terraform output values
      - name: Get S3 Bucket Name
        id: bucket_output
        run: echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_ENV

      - name: Upload Files to S3 Bucket
        run: |
          aws s3 sync ./Webfile/honey-static-webapp s3://$bucket_name --acl private
