name: Deploy Static Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve
        # Capture Terraform output values

      - name: Get S3 Bucket Name
        id: bucket_output
        run: |
          bucket_name=$(terraform output -raw bucket_name)
          echo "bucket_name=$bucket_name" >> $GITHUB_ENV

      - name: Upload to s3
        uses: ricardoapaes/action-s3-upload@latest
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: ${{ env.bucket_name}}
          src: ./Webfile/honey-static-webapp
          filename: honey-static-webapp
          metadata: cache-control=max-age=86400
          region: us-east-1
