name: Deploy static website

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ $default-branch]

jobs:
  build:
    name: build and define runner
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: checkout code
        uses: actions/checkout@v4

      - name: set up terraform on the runner
        uses: hashicorp/setup-terraform@v3

      - name: run terraform init on the runner
        #working-directory: .
        run: terraform init
      - name: run terraform apply on the runner
        run: terraform apply -auto-approve









